##### Fetch All #####
GET http://localhost:3000/api/1/select/users HTTP/1.1
Authorization: yourAuthorization

##### Fetch One #####
GET http://localhost:3000/api/1/select/users?id=1 HTTP/1.1
Authorization: yourAuthorization

##### Insert Values #####
POST http://localhost:3000/api/1/insert/ HTTP/1.1
Authorization: yourAuthorization
Content-Type: application/json

{
    "table": "users",
    "columns": ["fullName", "email", "password"],
    "values": ["Value", "Value", "Value"]
}

#### Delete Value ####
DELETE http://localhost:3000/api/1/delete/ HTTP/1.1
Authorization: silva
Content-Type: application/json

{
    "table": "users",
    "value": {
        "Colum": "Value"
    }
}